routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes([ 'register' => false ]);

Route::middleware('auth')->group(function () {

	Route::get('/home', 'HomeController@index')->name('home');
	Route::post('/video', 'VideoController@store')->name('video.store');

});

app/User.php
<?php

namespace App;

use App\Video;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function videos(){
        return $this->hasMany(Video::class);
    }
}

app/Video.php
<?php

namespace App;

use App\User;
use Illuminate\Database\Eloquent\Model;

class Video extends Model
{
    protected $fillable = ['title', 'video_url', 'gif_url', 'user_id'];

    public function user(){
    	
    	return $this->belongsTo(User::class);

    }

    public function getFullVideoUrlAttribute(){

    	if($this->video_url){
    		return config('app.s3_url') . '/' . $this->video_url;
    	}
    	
    }

    public function getFullGifUrlAttribute(){

    	if($this->gif_url){
    		return config('app.s3_url') . '/' . $this->gif_url;
    	}

    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/VideoController.php
<?php

namespace App\Http\Controllers;

use App\Video;
use FFMpeg\Media\Gif;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use FFMpeg\Coordinate\TimeCode;
use FFMpeg\Coordinate\Dimension;
use FFMpeg\Filters\Video\ClipFilter;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use App\Http\Requests\StoreVideoRequest;
use Pbmedia\LaravelFFMpeg\FFMpegFacade as FFMpeg;

class VideoController extends Controller
{
    public function store(StoreVideoRequest $request){

    	//store to s3 and get url
    	$video = Video::create([
    		'title' => $request->input('title'),
    		'video_url' => '',
            'gif_url' => '',
    		'user_id' => Auth::id()
    	]);

        //store video locally in order to be able to generate gif with ffmpeg

    	$folder_path = 'videos/'.$video->id;
        $video_name = Str::slug($request->input('title'));  

        $video_local_url = Storage::disk('local')->putFileAs(
            $folder_path, 
            $request->file('video'),
            $video_name.'.webm'
        );

        //generate gif and store it locally

        $full_video_path = $folder_path.'/'.$video_name;
        $gif_path = storage_path('app/'.$full_video_path.'.gif');

        FFMpeg::fromDisk('local')
            ->open($full_video_path.'.webm')
            ->gif(TimeCode::fromSeconds(0), new Dimension(640, 480), 1)
            ->save($gif_path);

        //get gif contents

        $gif = Storage::disk('local')->get($full_video_path.'.gif');

        //storeg both files on s3

        $video_url = Storage::disk('s3')->putFileAs(
            $folder_path, 
            $request->file('video'),
            $video_name.'.webm'
        );

        $gif_url = Storage::disk('s3')->put(
            $folder_path.'/'.$video_name.'.gif', 
            $gif
        );

    	$video->video_url = $video_url;
        $video->gif_url = $folder_path.'/'.$video_name.'.gif';
    	$video->save();

        //delete local files

        Storage::disk('local')->delete($video_url);
        Storage::disk('local')->delete($folder_path.'/'.$video_name.'.gif');

    	return response()->json([
    		'status' => 'success',
    		'video_url' => $video_url,
            'gif_url' => $folder_path.'/'.$video_name.'.gif'
    	]);

    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div id="app" class="container">
    <div class="row justify-content-center">
        <div class="col-md-3 mb-3">
            <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                <a class="nav-link active" id="v-pills-record-tab" data-toggle="pill" href="#v-pills-record" role="tab" aria-controls="v-pills-record">Record video</a>
                <a class="nav-link" id="v-pills-uploads-tab" data-toggle="pill" href="#v-pills-uploads" role="tab" aria-controls="v-pills-uploads">Uploads</a>
            </div>
        </div>
        <div class="col-md-9">
            <div class="tab-content" id="v-pills-tabContent">
                <div class="tab-pane fade show active" id="v-pills-record" role="tabpanel" aria-labelledby="v-pills-record-tab">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">Record video</div>

                            <div class="card-body">
                                <input v-model="title" class="form-control mb-3" type="text" placeholder="Enter a name for the video">
                                <video style="width: 100%" id="myVideo" class="video-js vjs-default-skin"></video>
                                <button @click="uploadVideo" id="uploadVideo" class="btn btn-primary mt-4 d-none">Upload Video</button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="tab-pane fade" id="v-pills-uploads" role="tabpanel" aria-labelledby="v-pills-uploads-tab">
                    <div class="tab-pane fade show active" id="v-pills-record" role="tabpanel" aria-labelledby="v-pills-record-tab">
                        <div class="col-12">
                            <div class="card">
                                <div class="card-header">Uploads</div>
                                <div class="card-body">
                                    @foreach(Auth::user()->videos()->latest()->get() as $video)

                                    <div class="card mb-2">
                                      <div class="card-body">
                                        <h5 class="card-title">{{$video->title}}</h5>
                                         <a target="_blank" href="{{ $video->full_video_url }}" class="card-link">{{ $video->full_video_url }}</a>
                                         <a target="_blank" href="{{ $video->full_gif_url }}" class="card-link">{{ $video->full_gif_url }}</a>
                                      </div>
                                    </div>
                                    @endforeach
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="tab-pane fade" id="v-pills-messages" role="tabpanel" aria-labelledby="v-pills-messages-tab">...</div>
                <div class="tab-pane fade" id="v-pills-settings" role="tabpanel" aria-labelledby="v-pills-settings-tab">...</div>
            </div>
        </div>
    </div>
</div>

@push('scripts')

<script>
    var app = new Vue({
      el: '#app',
      mounted: function(){

        this.player = videojs('myVideo', {
            // video.js options
            controls: true,
            loop: false,
            fluid: false,
            width: 320,
            height: 400,
            plugins: {
                record: {
                    image: false,
                    audio: true,
                    video: true,
                    debug: true,
                    maxLength: 900,
                }
            }
        });

        this.player.on('startRecord', function() {
            $('#uploadVideo').addClass('d-none');
        });

        this.player.on('finishRecord', function() {
            $('#uploadVideo').removeClass('d-none');
        });
      },
      data: {
        player: null,
        title: null
      },
      methods: {
        uploadVideo: function(){

            if(this.title == '' || this.title == null){
                
                alert("Please specify a name for the video");

            }else{

                var formData = new FormData();
                var blob = this.player.recordedData;

                formData.append('video', blob, blob.name);
                formData.append('title', this.title);

                axios.post('video', formData).then(function (response) {

                    alert("Video uploaded successfully");
                
                })
                .catch(function (error) {
                
                    alert("There was an error");
                    window.location.reload();
                
                });

            }
        }
      }
    })

</script>

@endpush

@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'SalesVid') }}</title>

    <!-- RECORD RTC -->
    <script src="https://cdn.WebRTC-Experiment.com/RecordRTC.js"></script>

    <!-- VIDEO JS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/video.js/7.5.4/video-js.min.css"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/video.js/7.5.4/video.min.js"></script>

    <!-- VIDEOJS RECORD -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/videojs-record/3.6.0/css/videojs.record.css"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/videojs-record/3.6.0/videojs.record.js"></script>
    
    <!-- ADAPTER -->
    <script src="https://webrtc.github.io/adapter/adapter-latest.js"></script>

    <!-- VUE -->

    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'SalesVid') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>

    @stack('scripts')
</body>
</html>